name: CI/CD to Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/oj-backend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/oj-backend:latest 
        
      - name: Build and Push Worker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/oj-worker:latest ./workers
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/oj-worker:latest 
        
      - name: Deploy To GCP via SSH
        uses : appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_KEY }}
          script: |
            cd ~/online-judge-backend
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/oj-backend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/oj-worker:latest
            docker compose down
            docker compose up -d
            



        
      